"""Added Targets Table_2

Revision ID: 5c8e5d3feee4
Revises: 619d82bcb278
Create Date: 2026-06-06 18:20:42.608757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c8e5d3feee4'
down_revision: Union[str, Sequence[str], None] = '619d82bcb278'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('targets', sa.Column('url', sa.String(), nullable=False))
    op.drop_column('targets', 'base_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('targets', sa.Column('base_url', sa.VARCHAR(), nullable=False))
    op.drop_column('targets', 'url')
    # ### end Alembic commands ###
