"""changed database structure

Revision ID: 77bd078d8dc1
Revises: b7c9d2e4f6a8
Create Date: 2026-06-15 19:00:59.437408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77bd078d8dc1'
down_revision: Union[str, Sequence[str], None] = 'b7c9d2e4f6a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'owner_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('smoke_test_run_results', 'finished_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('smoke_test_run_results', 'finished_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('projects', 'owner_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
